name: Feature Branch CI

on:
  push:
    branches:
      - "feature/**"

jobs:
  build-test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4


      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build an test with maven
        run: mvn -B test --file pom.xml